export const SERVER_API = "http://localhost:5000";
export const CLIENT_URL = "http://localhost:5173";
export const EASY_PARAGRAPH = [
    "since well off get would he another lead in hand those general govern because turn way take both stand make for because on when system keep eye one many possible develop we own might possible as to way problem than it even back make public you great time house you good man should what have or say time a too turn stand plan school very too any set just present take where what fact school know all year before course the up then form run need develop plan what again point tell this turn a some you day open consider each more both with than also system",
    "general number such plan mean think child like word form give develop on course nation govern can other follow by for eye lead who long look same form last great say show eye year only just in man might long life under but world seem such see too here nation most as life great since own may time find now both form well after never may but want year tell that between begin to under only large would develop have govern could through where home early eye all stand where when around new then no much well play place as can way first when could stand he",
    "only from between man part this large must new go look around into thing end and over even little change world word those eye word high on out real she world through hold need get large open use could from say point last little head plan to you want there play group before than they number world form from old go while who order for large nation take first any use help few stand know state work there child fact work plan very home system it order fact up or through should own how come person change write most small any not each child now might",
    "so find part by consider develop up down become get before have would much that even early work life eye place also we all life first from place way to open part never without through since much right long to call however by course few open program large that early interest it would both day use what each too form late first be without with year thing another of home follow against write go still have new over change open line be without too even become real work even by all but consider who home place during long for year people few get house call turn go find both feel however you ask most must well people one",
    "point keep under too even good can people as most program as set most too person not off about come number at late course many have now there however move may use even man show who have well system up need these than number show open through have home but like must because it govern thing course most increase end may open child want last place when open people what all most few down in show help many out think the become many can only increase now if also well little real around follow more old govern have keep off while few use set well a if during very long same school leave while hold will because get"
];

export const MEDIUM_PARAGRAPH = [
    "He place, see great much 'playl help present Any without day mean feel time while, way know may than mean other: or present both well no nation early, go new play, ask consider (look) because go long time small part know stand, to home this become but move, from early should school program he nation I take, Then he she, number well any no help, take keep too become, write between Great which Little other general know these lead, follow help good too, increase write, great might, come head, child between from haven t again well nation possible during Another govern out this who over only program on some",
    'The think most what any eye time, system public, place out under program, Part because each real change; small go mustn t say! Consider see thing he number form person up same, man write. Show but Public find a what long; (of) say No other can up, know old because, more one day year write? Public so Govern hold with (such) real time state call, now might own, by "those" run, program hold see right, look find, order that Problem on, own great home, more general man and end hold world at these get begin much, possible late face! Very "have" thing think come could. same, of day get want general open',
    'There much little have problem, well up there form might how when find form, home it write around other great help, public set head would by i What would say find get come, general problem any those early Last not say small! It against with, first home, call during seem say, person turn system course head Now both plan one, form this possible, point leave, end of man, back look, man it, what nation, also of seem need. Those by way well, could little old, for lead about part each still set, come if at make, what she place off to I but many than "other" not eye mean after number, could begin increase, of long,',
    "Eye high, around may, into also I man place - call, more lead increase, to good, again long, few more, up then another. Without interest than, or how, we (into) more find, interest people. Give mustn't with all mean, eye then man or now. Any a,Help seem of; use, place form long, good high will. End consider. Begin open for, he take long well around too move run people consider with, tell from place present, about you not long way, for course, here so back, more with. Turn or from Way move, good other with more last. Like well they show public how year hand can't work again (like) off: hold leave wouldn't find, say day back each, go see, about because small course",
]

export const HARD_PARAGRAPH = [
    "Never so head but, and 20 many have, plan consider would long line Such around. At course develop follow play open Become seem system, place give, out place, person 31 new - house end public, like - have here, 45 6848 she that after find be, what same keep might while small between house each stand Seem can I way consider because 9013 use out 95 real not stand year old 825 3598 turn face change. Follow time here well 217 may help here, year 7267 govern great! Again know. Over since, during run last open, program line year make, and no life both, begin through even first never general we some",
    'Face last, point for Still large, follow those use end She line know come 91 make. Problem still say how, think see they in nation, still present, again I course 4757 little present, interest 894 then as, here set 604 they, who seem set all New part from if For 788 24 both those nation, day or 416 now. Ask leave. House interest, 7 that 2691 these! Year 8153 home 57 develop hand face, now that, people tell. since form more like govern who, 3312 than think, too "out" write, state those last, for place, point of 56 consider form, 5 can, then set another at nation which, off under, show 9106 state.',
    "Both however, stand under state child 1 problem 771 word, off that; a, 2 general for? More while, couldn’t won't but? One such, between would, another both they play, we last the, more when 9 on, couldn’t while leave Many we hold may! Again seem house because see State child - we? Some 4994 life Think from nation between since develop these a time in hold 3 small Do on. Those public it out great (I) what general, write 25 down open 5 long world for open need, same course from first become seem, ask number, could know, way stand same because or no when as take which would problem, own against, another",
]
